-- DISABLED: pg_search (required for BM25 indexes) depends on pg_trgm which is deprecated on Neon
-- All BM25 index creations below are skipped on Neon free tier
-- If you need full-text search, consider using pgvector or external search service (e.g. Meilisearch)
